// Generated by GitHub Copilot - Sep-27-2026
// Shared AI ordering endpoint used by BOTH the AI Pizza Assistant and the Smart Meal
// Builder on the frontend. Flow: user text -> Gemini (primary) -> fallback parser
// (only if Gemini fails/times out/returns invalid data) -> MongoDB validation ->
// authoritative pricing -> cart-ready response. The Gemini API key never leaves the backend.

const { parseOrderWithGemini, parseOrderWithSecondaryGemini } = require('../services/geminiService');
const { parse: parseFallback } = require('../services/fallbackParser');
const { validateAndPrice } = require('../services/orderValidation');

const MAX_INPUT_LENGTH = 500;

/**
 * Registers the /api/ai/order endpoint on the given Express app.
 * @param {import('express').Express} app
 * @param {import('mongodb').MongoClient} mongoclient
 * @param {string} url - MongoDB connection URL.
 * @param {string} dbName
 */
function registerAiRoutes(app, mongoclient, url, dbName) {
  app.post('/api/ai/order', (req, res) => {
    const text = req.body && typeof req.body.text === 'string' ? req.body.text.trim() : '';

    // Input validation at the system boundary: reject empty or oversized input up front.
    if (!text) {
      return res.status(400).json({ success: false, message: 'Please describe what you would like to order.' });
    }
    if (text.length > MAX_INPUT_LENGTH) {
      return res.status(400).json({ success: false, message: `Please keep your request under ${MAX_INPUT_LENGTH} characters.` });
    }

    mongoclient.connect(url, async (error, conn) => {
      if (error) {
        console.log('DB Connection Error:', error.message);
        return res.status(500).json({ success: false, message: 'Database connection failed. Nothing was added to your cart.' });
      }

      try {
        const db = conn.db(dbName);
        const [pizzas, ingredients] = await Promise.all([
          db.collection('pizzas').find().toArray(),
          db.collection('ingredients').find().toArray()
        ]);

        let parsed;
        let aiError;
        let aiPath = 'primary-gemini';

        try {
          parsed = await parseOrderWithGemini(text, { pizzas, ingredients });
        } catch (err) {
          aiError = err.message;
          aiPath = 'secondary-gemini';

          try {
            parsed = await parseOrderWithSecondaryGemini(text, { pizzas, ingredients });
          } catch (secondaryErr) {
            console.log('Primary and secondary Gemini unavailable, using fallback parser:', secondaryErr.message);
            aiError = `${err.message}; secondary model also failed: ${secondaryErr.message}`;
            aiPath = 'fallback-parser';
            parsed = parseFallback(text);
          }
        }

        const usedFallback = aiPath === 'fallback-parser';

        if (!parsed || !Array.isArray(parsed.items) || parsed.items.length === 0) {
          return res.json({
            success: true,
            usedFallback,
            aiError,
            intent: parsed?.intent || 'UNKNOWN',
            availableItems: [],
            unavailableItems: [],
            cartItems: [],
            total: 0,
            anyAdded: false,
            message: "I couldn't understand an order in that message. Try something like \"Add a Margherita with extra cheese\"."
          });
        }

        const result = validateAndPrice(parsed, { pizzas, ingredients });

        return res.json({
          success: true,
          usedFallback,
          aiError,
          aiPath,
          ...result
        });
      } catch (err) {
        console.error('AI order processing error:', err.message);
        return res.status(500).json({ success: false, message: 'Something went wrong processing your request. Nothing was added to your cart.' });
      } finally {
        conn.close();
      }
    });
  });
}

module.exports = { registerAiRoutes };
