// Generated by GitHub Copilot - Sep-28-2026
// Secondary natural-language parser used ONLY when Gemini is unavailable, times out,
// or returns invalid/unusable structured data. Its output still has to pass through
// the same MongoDB validation pipeline as the Gemini path - it is never trusted directly.
//
// This parser is intentionally more general than a fixed phrase list: it strips any
// leading combination of common filler/verb words (rather than a handful of exact
// phrases), understands "for N people" group-size requests, and understands
// "remove X ... add/only Y" and "only X and Y" customization requests that describe a
// pizza purely by its toppings instead of a named menu dish.

const { extractLeadingQuantity, extractPeopleCount, servingQuantityForPeople } = require('./menuMatcher');

const FILLER_WORDS = new Set([
  'please', 'can', 'you', 'could', 'i', 'want', 'to', 'would', 'like',
  'add', 'build', 'make', 'create', 'order', 'get', 'give', 'need', 'prepare',
  'me', 'us', 'my', 'our', 'a', 'an', 'the', 'meal', 'for', 'that'
]);

const LEADING_ARTICLE = /^(a|an|the)\s+/i;

/**
 * Strips any leading run of common filler/verb words (e.g. "please can you build me a")
 * so the remaining text starts at the first meaningful word, without relying on a fixed
 * list of exact multi-word phrases.
 * @param {string} text
 * @returns {string}
 */
function stripLeadingFillers(text) {
  const words = text.trim().split(/\s+/).filter(Boolean);
  let start = 0;
  while (start < words.length - 1 && FILLER_WORDS.has(words[start].toLowerCase())) {
    start++;
  }
  return words.slice(start).join(' ');
}

function cleanFragment(name) {
  return name.replace(LEADING_ARTICLE, '').trim().replace(/[.?!]+$/g, '').trim();
}

/**
 * Splits a comma/"and"-separated list of topping phrases into individual names.
 * @param {string} text
 * @returns {string[]}
 */
function splitToppings(text) {
  return text
    .split(/,|\band\b/i)
    .map(t => t.trim())
    .filter(Boolean);
}

/**
 * Detects requests that describe a pizza purely by its toppings rather than by a named
 * preset dish - either "remove X ... add/with only Y" (modifying a named pizza that our
 * menu can't actually modify, so we build it fresh from just the remaining toppings) or
 * "... only X and Y" (no preset pizza implied at all).
 * @param {string} text
 * @returns {{ type: 'custom', name: string, quantity: number, toppings: Array<{name:string,quantity:number}> } | null}
 */
function tryParseCustomization(text) {
  const removeAddMatch = text.match(/(?:remove|without)\s+(.+?)\s+(?:and\s+)?(?:add|with)\s+(?:only\s+)?(.+)$/i);
  if (removeAddMatch) {
    const toppings = splitToppings(removeAddMatch[2]).map(name => ({ name: cleanFragment(name), quantity: 1 })).filter(t => t.name);
    if (toppings.length) {
      return { type: 'custom', name: 'Custom Pizza', quantity: 1, toppings };
    }
  }

  const onlyMatch = text.match(/\bonly\s+(.+)$/i);
  if (onlyMatch) {
    const toppings = splitToppings(onlyMatch[1]).map(name => ({ name: cleanFragment(name), quantity: 1 })).filter(t => t.name);
    if (toppings.length) {
      return { type: 'custom', name: 'Custom Pizza', quantity: 1, toppings };
    }
  }

  return null;
}

/**
 * Best-effort natural-language parse of a pizza order request. Handles a single
 * pizza + toppings, a pure-toppings custom pizza, a "for N people" group order with
 * no specific dish named, and independent multi-item lists ("a pizza and Coke").
 * Multi-pizza-with-per-pizza-toppings phrasing (e.g. "two pizzas, one with X and one
 * with Y") is intentionally left to Gemini, which understands that structure natively.
 * @param {string} text - Raw user input.
 * @returns {{ intent: string, items: Array<object> }}
 */
function parse(text) {
  const original = (text || '').trim();
  if (!original) {
    return { intent: 'UNKNOWN', items: [] };
  }

  const { peopleCount, rest: afterPeople } = extractPeopleCount(original);
  const effectiveQuantity = peopleCount ? servingQuantityForPeople(peopleCount) : null;
  const intent = peopleCount ? 'BUILD_MEAL' : 'ADD_TO_CART';

  const customItem = tryParseCustomization(afterPeople);
  if (customItem) {
    if (effectiveQuantity) customItem.quantity = effectiveQuantity;
    return { intent, items: [customItem] };
  }

  let working = stripLeadingFillers(afterPeople);

  const { quantity, rest } = extractLeadingQuantity(working);
  working = rest;
  const finalQuantity = effectiveQuantity || quantity || 1;

  if (/\bwith\b/i.test(working)) {
    const withSplit = working.split(/\bwith\b/i);
    const pizzaPart = cleanFragment(withSplit[0]);
    const toppingsPart = withSplit.slice(1).join(' with ').trim();

    const toppings = toppingsPart
      ? splitToppings(toppingsPart).map(name => ({ name: cleanFragment(name), quantity: 1 })).filter(t => t.name)
      : [];

    // No dish named at all (not even a generic "pizza" mention) and no group-size signal
    // to justify recommending one - there's nothing real to validate against the menu.
    if (!pizzaPart && !peopleCount) {
      return { intent: 'UNKNOWN', items: [] };
    }

    return {
      intent,
      items: [{ type: 'pizza', name: pizzaPart, quantity: finalQuantity, toppings }]
    };
  }

  const segments = working
    .split(/,|\band\b/i)
    .map(cleanFragment)
    .filter(Boolean);

  if (segments.length === 0) {
    if (peopleCount) {
      // A group-size request with no specific dish named (e.g. "a meal for 10 people") -
      // still produce an item so the pipeline recommends and prices a real menu pizza.
      return {
        intent,
        items: [{ type: 'pizza', name: '', quantity: finalQuantity, toppings: [] }]
      };
    }
    return { intent: 'UNKNOWN', items: [] };
  }

  return {
    intent,
    items: segments.map((name, index) => ({
      type: 'pizza',
      name,
      quantity: index === 0 ? finalQuantity : 1,
      toppings: []
    }))
  };
}

module.exports = { parse };

