// Generated by GitHub Copilot - Sep-27-2026
// Sends the user's raw natural-language request to Gemini and returns Gemini's
// structured understanding of it. Gemini is responsible for understanding intent,
// pizzas, toppings and quantities - it is NEVER treated as the source of truth for
// the menu or for pricing. Every item Gemini returns is validated against MongoDB
// by the caller.

const GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
const SECONDARY_GEMINI_MODEL = process.env.SECONDARY_GEMINI_MODEL || 'gemini-3.5-flash-lite';
const GEMINI_TIMEOUT_MS = 10000;
const QUOTA_COOLDOWN_MS = 5 * 60 * 1000;

// Track cooldown per model instead of globally. If the primary model is rate-limited,
// the secondary model still gets a chance to interpret the request before we fall back
// to the local parser.
const quotaCooldownUntilByModel = new Map();

const SYSTEM_PROMPT_PRIMARY = `You are the natural-language understanding engine for a pizzeria ordering system.

Your ONLY job is to read the customer's message and extract their ordering intent as
structured JSON. You do NOT decide what is available and you do NOT calculate prices -
a separate backend system validates every item you return against the real menu database.

Rules you MUST follow:
1. Identify the overall intent: "ADD_TO_CART" for ordering/adding items, "BUILD_MEAL" when the
   user is asking you to build/put together a meal from a description, or "UNKNOWN" if the
   message is not an ordering request at all.
2. Extract EVERY pizza mentioned, not just the first one. If the user asks for multiple pizzas
   (e.g. "two chicken pizzas, one with extra cheese and mushrooms, and another with jalapenos"),
   return one separate item per pizza, each with its own toppings and quantity.
3. For every pizza, extract ALL of its requested toppings - never stop after finding the pizza
   name and ignore the toppings. A pizza with two toppings must produce a toppings array with
   two entries.
4. Extract quantities carefully. "2 pepperoni pizzas" -> quantity 2. If no quantity is stated,
   use 1. Quantities must never be dropped.
5. If the user mentions an item that is clearly meant to stand alone (not attached to a specific
   pizza), such as a drink or a side, return it as its own item with "type": "topping".
6. You will be given a reference list of the pizzeria's real menu item names below. Use it only
   to recognize when the user is clearly referring to one of these exact items (including minor
   wording differences like plurals, casing, typos, or the word "pizza"). Do NOT rename or
   "correct" the user's wording to a different real menu item just to be helpful, and do NOT
   invent a name that isn't a plausible reading of what the user said. If you are not confident
   the user means one of the listed real items, return their wording as given (do not fabricate
   a new product).
7. Never invent items, prices, or availability. You do not know real-time availability - that is
   determined by the backend after you respond.
8. If the user describes a pizza purely by listing toppings with no named preset dish (e.g. "a
   pizza with only tomato and jalapenos"), OR asks to take a named pizza and remove/add toppings
   (our preset pizzas are fixed whole dishes and cannot be modified item-by-item), return a
   "custom" type item containing ONLY the toppings that should end up on the pizza - ignore any
   removed toppings and do NOT also return the named preset pizza.
9. If the user asks for an order/meal "for N people" (or similar group-size language: guests,
   adults, folks) without naming a specific dish, do not leave items empty. Infer a reasonable
   quantity assuming one medium pizza serves about 3 people (quantity = ceil(N / 3)), pick your
   single best recommendation from the real menu pizzas list (taking any other stated preference
   like spice level or vegetarian into account), and return it as a normal "pizza" item with that
   quantity.
10. Be tolerant of typos, casual phrasing, slang, and grammar mistakes. Interpret the user's
    intent the way a helpful, attentive waiter would, rather than requiring exact menu wording.
11. Always respond using the required JSON schema only. Do not include any prose, markdown, or
    explanation outside the JSON.`;

const SYSTEM_PROMPT_SECONDARY = `You are the backup natural-language understanding engine for a pizzeria ordering system.

Your job is to be more forgiving and conversational than the primary parser. Read the customer's
message and turn it into structured JSON that the backend can validate against MongoDB.

Rules you MUST follow:
1. Identify intent as "ADD_TO_CART", "BUILD_MEAL", or "UNKNOWN".
2. Interpret vague requests like "I want something spicy" as a helpful recommendation using a
  real menu pizza from the provided menu list. Choose the closest real item and keep the result
  grounded in the menu reference.
3. If the user describes a pizza by toppings only, or asks to remove one topping and add another,
  return a "custom" item containing only the toppings that should remain.
4. If the user mentions "for N people", infer a sensible pizza quantity using the menu reference
  and the rest of the request. Do not leave the item list empty if a real menu choice can be made.
5. Support casual phrasing, spelling mistakes, and incomplete sentences. Favor helpful interpretation
  over literal wording.
6. Never invent menu items or prices.
7. Always return JSON only, matching the required schema.`;

const RESPONSE_SCHEMA = {
  type: 'OBJECT',
  properties: {
    intent: { type: 'STRING', enum: ['ADD_TO_CART', 'BUILD_MEAL', 'UNKNOWN'] },
    items: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          type: { type: 'STRING', enum: ['pizza', 'topping', 'custom'] },
          name: { type: 'STRING' },
          quantity: { type: 'NUMBER' },
          toppings: {
            type: 'ARRAY',
            items: {
              type: 'OBJECT',
              properties: {
                name: { type: 'STRING' },
                quantity: { type: 'NUMBER' }
              },
              required: ['name']
            }
          }
        },
        required: ['type', 'name']
      }
    }
  },
  required: ['intent', 'items']
};

/**
 * Builds the reference menu block included in the Gemini prompt so Gemini can
 * recognize real item names without becoming the source of truth for them.
 * @param {Array<{name:string}>} pizzas
 * @param {Array<{tname?:string,name?:string}>} ingredients
 */
function buildMenuReference(pizzas, ingredients) {
  const pizzaNames = pizzas.map(p => p.name).join(', ');
  const toppingNames = ingredients.map(i => i.tname || i.name).join(', ');
  return `Real menu pizzas: ${pizzaNames}\nReal menu toppings: ${toppingNames}`;
}

function getCooldownUntil(modelName) {
  return quotaCooldownUntilByModel.get(modelName) || 0;
}

function markQuotaCooldown(modelName) {
  quotaCooldownUntilByModel.set(modelName, Date.now() + QUOTA_COOLDOWN_MS);
}

async function parseOrderWithGeminiModel(userText, menu, modelName, systemPrompt) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured');
  }

  if (Date.now() < getCooldownUntil(modelName)) {
    throw new Error(`Gemini model ${modelName} is in cooldown after a recent rate limit`);
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
  const menuReference = buildMenuReference(menu.pizzas, menu.ingredients);

  const body = {
    systemInstruction: {
      role: 'system',
      parts: [{ text: systemPrompt }]
    },
    contents: [
      {
        role: 'user',
        parts: [{ text: `${menuReference}\n\nCustomer request: "${userText}"` }]
      }
    ],
    generationConfig: {
      responseMimeType: 'application/json',
      responseSchema: RESPONSE_SCHEMA,
      temperature: 0.15
    }
  };

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), GEMINI_TIMEOUT_MS);

  let response;
  try {
    response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
      signal: controller.signal
    });
  } catch (err) {
    if (err.name === 'AbortError') {
      throw new Error(`Gemini model ${modelName} request timed out`);
    }
    throw new Error(`Gemini model ${modelName} request failed: ${err.message}`);
  } finally {
    clearTimeout(timeoutId);
  }

  if (!response.ok) {
    const errText = await response.text().catch(() => '');
    if (response.status === 429) {
      markQuotaCooldown(modelName);
    }
    throw new Error(`Gemini API error ${response.status}: ${errText.slice(0, 300)}`);
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error(`Gemini model ${modelName} returned an empty response`);
  }

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (err) {
    throw new Error(`Gemini model ${modelName} response was not valid JSON`);
  }

  if (!parsed || !Array.isArray(parsed.items)) {
    throw new Error(`Gemini model ${modelName} response did not match the expected schema`);
  }

  return {
    intent: typeof parsed.intent === 'string' ? parsed.intent : 'ADD_TO_CART',
    items: parsed.items
  };
}

/**
 * Calls Gemini with the user's natural-language order request and returns the
 * parsed structured intent. Throws on network failure, timeout, non-2xx status,
 * or unparsable/invalid JSON so the caller can fall back to the local parser.
 * @param {string} userText - The customer's raw natural-language request.
 * @param {{ pizzas: Array<object>, ingredients: Array<object> }} menu - Current MongoDB menu, used only as grounding context.
 * @returns {Promise<{ intent: string, items: Array<object> }>}
 */
async function parseOrderWithGemini(userText, menu) {
  return parseOrderWithGeminiModel(userText, menu, GEMINI_MODEL, SYSTEM_PROMPT_PRIMARY);
}

/**
 * Secondary model-backed parser used when the primary Gemini model fails or is rate-limited.
 * This is still AI-backed, but the prompt is more forgiving so broad and vague requests can
 * be interpreted more naturally before we ever fall back to the local parser.
 * @param {string} userText
 * @param {{ pizzas: Array<object>, ingredients: Array<object> }} menu
 * @returns {Promise<{ intent: string, items: Array<object> }>}
 */
async function parseOrderWithSecondaryGemini(userText, menu) {
  return parseOrderWithGeminiModel(userText, menu, SECONDARY_GEMINI_MODEL, SYSTEM_PROMPT_SECONDARY);
}

module.exports = { parseOrderWithGemini, parseOrderWithSecondaryGemini };
