// Generated by GitHub Copilot - Sep-27-2026
// Matches free-text pizza/topping names against the authoritative MongoDB menu.
// MongoDB is always the source of truth; this module never invents items.

const WORD_NUMBERS = {
  one: 1, two: 2, three: 3, four: 4, five: 5, six: 6,
  seven: 7, eight: 8, nine: 9, ten: 10
};

/**
 * Normalizes free text into a comparable set of stemmed tokens.
 * Strips punctuation, lowercases, removes the filler word "pizza"/"pizzas" (tolerating
 * minor typos like "piza"), and naively de-pluralizes so "mushrooms" and "Mushrooms" line up.
 * @param {string} text
 * @param {{ keepPizzaWord?: boolean }} [opts]
 * @returns {string[]}
 */
function tokenize(text, opts = {}) {
  if (!text) return [];
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map(w => (w.length > 3 && w.endsWith('s') ? w.slice(0, -1) : w))
    .filter(w => {
      if (opts.keepPizzaWord) return true;
      if (w === 'pizza' || w === 'pizzas') return false;
      if (w.length >= 4 && levenshtein(w, 'pizza') <= 1) return false;
      return true;
    });
}

function tokenSetEqual(a, b) {
  if (a.length === 0 || b.length === 0) return false;
  if (a.length !== b.length) return false;
  const setA = new Set(a);
  const setB = new Set(b);
  if (setA.size !== setB.size) return false;
  for (const t of setA) if (!setB.has(t)) return false;
  return true;
}

/**
 * Classic edit-distance between two short strings, used to tolerate typos
 * (e.g. "chiken" vs "chicken") when matching menu item names.
 */
function levenshtein(a, b) {
  if (a === b) return 0;
  const al = a.length;
  const bl = b.length;
  if (al === 0) return bl;
  if (bl === 0) return al;

  let prev = new Array(bl + 1);
  for (let j = 0; j <= bl; j++) prev[j] = j;

  for (let i = 1; i <= al; i++) {
    const curr = [i];
    for (let j = 1; j <= bl; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + cost);
    }
    prev = curr;
  }
  return prev[bl];
}

/** Whether two tokens are the same or close enough to be a likely typo of each other. */
function tokensClose(a, b) {
  if (a === b) return true;
  const maxDist = Math.min(a.length, b.length) <= 4 ? 1 : 2;
  return levenshtein(a, b) <= maxDist;
}

/**
 * Counts how many query tokens have a close (exact-or-typo) match among candidate
 * tokens, each candidate token usable at most once.
 */
function fuzzyOverlapScore(queryTokens, candidateTokens) {
  const used = new Array(candidateTokens.length).fill(false);
  let count = 0;
  for (const qt of queryTokens) {
    for (let i = 0; i < candidateTokens.length; i++) {
      if (!used[i] && tokensClose(qt, candidateTokens[i])) {
        used[i] = true;
        count++;
        break;
      }
    }
  }
  return count;
}


/**
 * Finds the best match for a pizza name in the MongoDB pizza collection: first an
 * exact token-set match, then a typo/wording-tolerant fuzzy match, then falls back
 * to up to 3 partial-overlap suggestions when nothing is close enough.
 * A purely generic request (e.g. "a pizza", "pizza") with no distinguishing tokens
 * is treated as "recommend anything" and resolves to the highest-rated real pizza,
 * rather than being reported unavailable.
 * @param {string} name - Free-text pizza name extracted from the user's request.
 * @param {Array<{name:string,price:number,_id?:any,rating?:number}>} pizzas - Menu pizzas from MongoDB.
 */
function matchPizza(name, pizzas) {
  const queryTokens = tokenize(name);

  if (queryTokens.length === 0 && pizzas.length > 0) {
    const recommended = [...pizzas].sort((a, b) => (b.rating || 0) - (a.rating || 0))[0];
    return { match: recommended, suggestions: [], recommended: true };
  }

  const exact = pizzas.find(p => tokenSetEqual(queryTokens, tokenize(p.name)));
  if (exact) return { match: exact, suggestions: [] };

  const scored = pizzas
    .map(p => {
      const candidateTokens = tokenize(p.name);
      return { pizza: p, score: fuzzyOverlapScore(queryTokens, candidateTokens), candidateLen: candidateTokens.length };
    })
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score || a.pizza.name.localeCompare(b.pizza.name));

  const bestFuzzy = scored.find(s => s.score / queryTokens.length >= 0.6 && s.score / s.candidateLen >= 0.5);
  if (bestFuzzy) return { match: bestFuzzy.pizza, suggestions: [] };

  return { match: null, suggestions: scored.slice(0, 3).map(s => s.pizza.name) };
}

/**
 * Finds the best match for a topping/ingredient name in MongoDB: an exact token-set
 * match first, then a typo/wording-tolerant fuzzy match.
 * @param {string} name - Free-text topping name.
 * @param {Array<{tname?:string,name?:string,price:number,_id?:any}>} ingredients - Menu ingredients from MongoDB.
 */
function matchIngredient(name, ingredients) {
  const queryTokens = tokenize(name);
  if (queryTokens.length === 0) return null;

  const exact = ingredients.find(i => tokenSetEqual(queryTokens, tokenize(i.tname || i.name || '')));
  if (exact) return exact;

  const scored = ingredients
    .map(i => {
      const candidateTokens = tokenize(i.tname || i.name || '');
      return { ingredient: i, score: fuzzyOverlapScore(queryTokens, candidateTokens), candidateLen: candidateTokens.length };
    })
    .filter(s => s.score > 0 && s.score / queryTokens.length >= 0.6 && s.score / s.candidateLen >= 0.5)
    .sort((a, b) => b.score - a.score);

  return scored[0]?.ingredient || null;
}

/**
 * Parses a leading quantity phrase (numeric or spelled out) from a text fragment.
 * @param {string} text
 * @returns {{ quantity: number, rest: string }}
 */
function extractLeadingQuantity(text) {
  const trimmed = text.trim();
  const numericMatch = trimmed.match(/^(\d+)\s+(.*)$/);
  if (numericMatch) {
    return { quantity: parseInt(numericMatch[1], 10) || 1, rest: numericMatch[2] };
  }
  const wordMatch = trimmed.match(/^(one|two|three|four|five|six|seven|eight|nine|ten)\s+(.*)$/i);
  if (wordMatch) {
    return { quantity: WORD_NUMBERS[wordMatch[1].toLowerCase()] || 1, rest: wordMatch[2] };
  }
  return { quantity: 1, rest: trimmed };
}

const PEOPLE_PATTERN = /\bfor\s+(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s*\+?\s*(?:people|persons?|guests?|adults?|folks)\b/i;

/**
 * Detects a "for N people/guests/..." clause anywhere in the text and strips it out,
 * so a group-size request like "build a meal for 10 people" doesn't get treated as a
 * literal (unmatchable) menu item name.
 * @param {string} text
 * @returns {{ peopleCount: number|null, rest: string }}
 */
function extractPeopleCount(text) {
  const match = text.match(PEOPLE_PATTERN);
  if (!match) return { peopleCount: null, rest: text };

  const raw = match[1].toLowerCase();
  const num = WORD_NUMBERS[raw] || parseInt(raw, 10);
  const rest = (text.slice(0, match.index) + text.slice(match.index + match[0].length))
    .replace(/\s+/g, ' ')
    .trim();

  return { peopleCount: Number.isFinite(num) && num > 0 ? num : null, rest };
}

/**
 * Rough heuristic for how many pizzas are needed to feed a group: one medium pizza
 * comfortably serves about 3 people.
 * @param {number} people
 */
function servingQuantityForPeople(people) {
  return Math.max(1, Math.ceil(people / 3));
}

module.exports = {
  tokenize,
  matchPizza,
  matchIngredient,
  extractLeadingQuantity,
  extractPeopleCount,
  servingQuantityForPeople
};
