// Generated by GitHub Copilot - Sep-27-2026
// Validates Gemini's (or the fallback parser's) structured items against the real
// MongoDB menu and computes authoritative pricing. This is the single convergence
// point both the Gemini path and the fallback path flow through, so both end up
// producing identical cart-ready output.

const { matchPizza, matchIngredient } = require('./menuMatcher');

/**
 * Validates every requested pizza/topping independently against MongoDB and builds
 * cart-ready line items, an availability breakdown, and a human-readable summary.
 * Pizza availability and topping availability are always evaluated separately:
 * an unavailable topping never blocks an otherwise-available pizza, and vice versa.
 * @param {{ intent: string, items: Array<object> }} parsed - Structured intent from Gemini or the fallback parser.
 * @param {{ pizzas: Array<object>, ingredients: Array<object> }} menu - Authoritative MongoDB menu data.
 */
function validateAndPrice(parsed, menu) {
  const availableItems = [];
  const unavailableItems = [];
  const cartItems = [];
  let total = 0;

  // Adds an available standalone ingredient (e.g. a drink/side, or a topping mentioned
  // with no attached pizza) directly as its own cart line item.
  function addStandaloneIngredient(ingredientMatch, quantity) {
    const price = ingredientMatch.price;
    const displayName = ingredientMatch.tname || ingredientMatch.name;
    availableItems.push({ name: displayName, quantity, price, toppings: [] });
    cartItems.push({
      id: `ai_${ingredientMatch._id || displayName}`,
      name: displayName,
      price,
      quantity,
      image: ingredientMatch.image,
      type: 'custom'
    });
    total += price * quantity;
  }

  const items = Array.isArray(parsed.items) ? parsed.items : [];

  for (const rawItem of items) {
    const quantity = Math.max(1, Math.floor(Number(rawItem.quantity) || 1));
    const requestedToppings = Array.isArray(rawItem.toppings) ? rawItem.toppings : [];

    if (rawItem.type === 'topping') {
      // Standalone item (e.g. a drink) not attached to any pizza.
      const ingredientMatch = matchIngredient(rawItem.name, menu.ingredients);
      if (!ingredientMatch) {
        unavailableItems.push({ name: rawItem.name, category: 'item', reason: 'not available on our current menu' });
        continue;
      }
      addStandaloneIngredient(ingredientMatch, quantity);
      continue;
    }

    if (rawItem.type === 'custom') {
      // A pizza described purely by its toppings (no preset menu dish involved) - e.g.
      // "a pizza with only tomato and jalapenos", or a preset pizza the user asked to
      // modify by removing/adding toppings, which our fixed-dish menu can't do, so it's
      // rebuilt fresh from just the toppings that should remain.
      const toppingResults = requestedToppings.map(t => {
        const topQty = Math.max(1, Math.floor(Number(t.quantity) || 1));
        return { requestedName: t.name, quantity: topQty, match: matchIngredient(t.name, menu.ingredients) };
      });

      const availableToppings = toppingResults.filter(t => t.match);
      const unavailableToppings = toppingResults.filter(t => !t.match);

      unavailableToppings.forEach(t => unavailableItems.push({
        name: t.requestedName,
        category: 'topping',
        reason: 'not available on our current menu'
      }));

      if (availableToppings.length === 0) {
        unavailableItems.push({
          name: rawItem.name || 'Custom Pizza',
          category: 'pizza',
          reason: 'none of the requested toppings are available on our current menu'
        });
        continue;
      }

      const unitPrice = availableToppings.reduce((sum, t) => sum + t.match.price * t.quantity, 0);
      const toppingNames = availableToppings.map(t => t.match.tname || t.match.name);
      const displayName = `Custom Pizza (${toppingNames.join(', ')})`;

      availableItems.push({
        name: 'Custom Pizza',
        quantity,
        price: 0,
        toppings: availableToppings.map(t => ({ name: t.match.tname || t.match.name, price: t.match.price, quantity: t.quantity }))
      });

      const idPart = availableToppings.map(t => t.match._id || t.match.tname || t.match.name).sort().join('-');
      cartItems.push({
        id: `ai_custom_${idPart}`,
        name: displayName,
        price: unitPrice,
        quantity,
        image: availableToppings[0].match.image,
        type: 'custom'
      });

      total += unitPrice * quantity;
      continue;
    }

    // type === 'pizza' (default)
    const { match: pizzaMatch, suggestions } = matchPizza(rawItem.name, menu.pizzas);

    // The fallback parser can't always tell a pizza request apart from a standalone
    // item request. If it isn't a real pizza and has no nested toppings, check whether
    // it's actually a real standalone ingredient (e.g. "add extra cheese") before giving up.
    if (!pizzaMatch && requestedToppings.length === 0) {
      const ingredientMatch = matchIngredient(rawItem.name, menu.ingredients);
      if (ingredientMatch) {
        addStandaloneIngredient(ingredientMatch, quantity);
        continue;
      }
    }

    const toppingResults = requestedToppings.map(t => {
      const topQty = Math.max(1, Math.floor(Number(t.quantity) || 1));
      const ingredientMatch = matchIngredient(t.name, menu.ingredients);
      return {
        requestedName: t.name,
        quantity: topQty,
        match: ingredientMatch
      };
    });

    const availableToppings = toppingResults.filter(t => t.match);
    const unavailableToppings = toppingResults.filter(t => !t.match);

    if (!pizzaMatch) {
      unavailableItems.push({
        name: rawItem.name,
        category: 'pizza',
        reason: 'not available on our current menu',
        suggestions
      });
      unavailableToppings.forEach(t => unavailableItems.push({
        name: t.requestedName,
        category: 'topping',
        reason: `not available on our current menu (requested with "${rawItem.name}")`
      }));
      // Per spec: do not add a topping standalone just because its pizza was unavailable,
      // but still tell the user it was skipped rather than silently dropping it.
      availableToppings.forEach(t => unavailableItems.push({
        name: t.match.tname || t.match.name,
        category: 'topping',
        reason: `not added because "${rawItem.name}" isn't available`
      }));
      continue;
    }

    unavailableToppings.forEach(t => unavailableItems.push({
      name: t.requestedName,
      category: 'topping',
      reason: `not available on our current menu (requested with "${pizzaMatch.name}")`
    }));

    const toppingsCostPerUnit = availableToppings.reduce((sum, t) => sum + t.match.price * t.quantity, 0);
    const unitPrice = pizzaMatch.price + toppingsCostPerUnit;
    const toppingNames = availableToppings.map(t => t.match.tname || t.match.name);
    const displayName = toppingNames.length ? `${pizzaMatch.name} (${toppingNames.join(', ')})` : pizzaMatch.name;

    availableItems.push({
      name: pizzaMatch.name,
      quantity,
      price: pizzaMatch.price,
      toppings: availableToppings.map(t => ({ name: t.match.tname || t.match.name, price: t.match.price, quantity: t.quantity }))
    });

    const toppingIdPart = availableToppings
      .map(t => t.match._id || t.match.tname || t.match.name)
      .sort()
      .join('-');
    const cartId = `ai_${pizzaMatch._id || pizzaMatch.name}${toppingIdPart ? `_${toppingIdPart}` : ''}`;

    cartItems.push({
      id: cartId,
      name: displayName,
      price: unitPrice,
      quantity,
      image: pizzaMatch.image,
      type: 'custom'
    });

    total += unitPrice * quantity;
  }

  const message = buildMessage(availableItems, unavailableItems);

  return {
    intent: parsed.intent || 'ADD_TO_CART',
    availableItems,
    unavailableItems,
    cartItems,
    total,
    anyAdded: cartItems.length > 0,
    message
  };
}

/**
 * Builds a concise, honest human-readable summary of what was/was not added.
 */
function buildMessage(availableItems, unavailableItems) {
  const addedNames = [];
  availableItems.forEach(item => {
    addedNames.push(item.quantity > 1 ? `${item.quantity}x ${item.name}` : item.name);
    item.toppings.forEach(t => addedNames.push(t.name));
  });

  const unavailableNames = unavailableItems.map(u => u.name);

  if (addedNames.length === 0 && unavailableNames.length === 0) {
    return "I couldn't find anything to add. Try describing a pizza you'd like, e.g. \"Add a Margherita with extra cheese\".";
  }
  if (addedNames.length === 0) {
    return `I couldn't add those items because they aren't available on our current menu: ${unavailableNames.join(', ')}.`;
  }
  if (unavailableNames.length === 0) {
    return `Added: ${addedNames.join(', ')}.`;
  }
  return `Added: ${addedNames.join(', ')}. Not available: ${unavailableNames.join(', ')}.`;
}

module.exports = { validateAndPrice };
